version: '3.8'

services:
  mcp-server:
    build: .
    container_name: mcp-linkedin-container
    ports:
      - "5001:5001"
    environment:
      - EXA_API_KEY=$[EXA_API_KEY]
    restart: unless-stopped